version: 2

build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-22.9
  jobs:
    pre_build:
      - jlpm
      - jlpm build
      - jlpm docs
      - cd python/jupyterlab_widgets && pyproject-build --no-isolation
      - cd python/widgetsnbextension && pyproject-build --no-isolation
      - cd python/ipywidgets && pyproject-build --no-isolation

python:
  install:
    - method: pip
      path: ./python/ipywidgets

conda:
  environment: docs/environment.yml
