name: docs
channels:
  - conda-forge
  - nodefaults
dependencies:
  - bqplot
  - build
  - ipykernel
  - jupyter_client
  - jupyterlab >=3,<4
  - jupyter-packaging
  - matplotlib-base
  - nbsphinx
  - nodejs=14
  - numpy
  - packaging
  - pandoc
  - python=3.10
  - recommonmark
  - scikit-image
  - scikit-learn
  - sphinx
  - sphinx_rtd_theme
  - sympy
  # lite deps
  - pip
  - doit
  - pkginfo
  - pip:
    - jupyterlite==0.1.0b15
    - jupyterlite-sphinx~=0.7.2
