name: Lint

on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'
      - name: yarn install, integrity, lint
        run: |
          yarn install --frozen-lockfile
          yarn run integrity
          pre-commit run --all-files --show-diff-on-failure
          # yarn run lint:check
