name: Test Docs

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        sudo apt-get install -y pandoc
        conda install 
    - uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        environment-file: docs/environment.yml
        activate-environment: ipywidget_docs
    - name: Install ipywidgets
      run: |
        which python
        which conda
        python --version
        conda info
        pip install file://$PWD#egg=ipywidgets
    - name: Build docs
      run: |
        which python
        which conda
        python --version
        conda info
        cd docs
        make html
