name: Test Docs

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        sudo apt-get install -y pandoc
    - name: Setup conda environment
      uses: matthewrmshin/conda-action@v1
      with:
        args: conda env create --file docs/environment.yml
    - name: Install ipywidgets
      run: |
        pip install file://$PWD#egg=ipywidgets
    - name: Build docs
      run: |
        cd docs
        make html
